version: "3.8"

services:
    laravel:
        build:
            context: ./laravel
            dockerfile: ../docker_configs/laravel/Dockerfile
        container_name: laravel
        restart: always
        volumes:
            - ./laravel:/var/www
        depends_on:
            - db
        networks:
            - environment_network

    angular:
        build:
            context: ./frontend
            dockerfile: ../docker_configs/angular/Dockerfile
        container_name: angular
        restart: always
        networks:
            - environment_network

    db:
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: party_go_admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - environment_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_ROOT_USER: root
            PMA_ROOT_PASSWORD: root
            PMA_ABSOLUTE_URI: http://localhost:5000/phpmyadmin/
        networks:
            - environment_network
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "5000:80"
        volumes:
            - ./docker_configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist/frontend:/usr/share/nginx/html
        depends_on:
            - laravel
            - angular
            - phpmyadmin
        networks:
            - environment_network
volumes:
    db-data:


networks:
    environment_network:
        driver: bridge
